### ISSUE TITLE
support tags for general taxonomy

### ISSUE THREAD

**Issue by ameshkov** [collinbarrett/FilterLists#65]
Practice shows, that it's hard for people to understand what this or that filter does, and description is often too vague or too long and does not help much.

Manual Tags:

- [X] `ads` - blocking ads, plain and simple
- [X] ~~`language: {lang code}` - filter is language specific. I'd like to emphasize, that filters are usually language-specific, and not region-specific.~~ [has its own taxonomy]
- [X] `privacy` - blocking trackers
- [X] `social` - blocking social widgets
- [X] `anti-adblock` - handles anti-adblocking scripts and warnings
- [X] `malware` - filter is supposed to block malicious URLs.
- [X] `phishing/scam` - filter is supposed to block phishing or scam URLs.
- [X] `cookies` - judging from the number of filters blocking those, it deserves its own tag.
- [X] `annoyances` - filter is supposed to block non-adverts annoying elements of the web pages. Filters in that category might be controversial as it's hard to give a common definition to what is annoyance:)
- [X] `ie` (#61)
- [X] `whitelist` (#34, [per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-413404032))
- [X] `crypto` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-365261525))
- [X] `nsfw` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-365263753))
- [X] `topical` (#385)
- [X] `Proxy` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-413404032))
- [X] `Search` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-413404032))
- [X] `Research` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-413404032))
- [X] ~~`Miscellaneous` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-413404032))~~ [won't add for now, seems nebulous]

Auto-Tags:

- [X] ~~`HTTP` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-412597260))~~ [indicating with orange/warning view/subscribe buttons]
- [X] ~~`New` ([per](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-412605562)) (could be "New to FilterLists" and/or "Newly Launched/Published")~~ [will be addressed in #386]
- [X] ~~`Archive.org` (#325)~~ [indicating with gray/secondary view/subscribe buttons]

Features TODO:

- [X] add line breaks between multiple tags
- [X] add dynamic colors (by tag value)
- [X] add tags to details expanders on mobile
- [X] ~~support sorting (by at least a list's first alphabetical tag) in grid~~ [migrated to #421]
- [X] ~~support "click-to-filter" by clicking on a tag for any list and having that tag autofill in the tags filter box (may or may not be easily possible)~~ [migrated to #391]
- [X] add new entities to seed API endpoints

**Comment by collinbarrett** [comment]
Great idea! Thanks. I agree that the descriptions are all over the place in terms of usefulness. Most of them (those in italics) are copied verbatim from the list maintainer's site somewhere. I'd love to improve these over time.

But, adding badges seems like a super helpful step. It is something I am planning on doing with #61 , #34 , #28 , #18 , #11 , & #7 , but these suggestions you made are great. I will add some or all of those as well.

Thanks. Keep the ideas coming if you have any more.

**Comment by elypter** [comment]
malware and phishing/scam should be two different categories. the one is about exploiting software bugs the other is about exploiting lack of expierience.

**Comment by collinbarrett** [comment]
should add a tag for `crypto`

**Comment by elypter** [comment]
Adult content should also be an option because there are some lists that include porn sites and some people use adblockers as a parenting tool.

**Comment by collinbarrett** [comment]
Capture @elypter 's suggestion of how to handle whitelists, etc. in this feature rather than as a syntax. See ([here](https://github.com/collinbarrett/FilterLists/issues/7#issuecomment-357214534) and [here](https://github.com/collinbarrett/FilterLists/issues/7#issuecomment-364911688)).

**Comment by collinbarrett** [comment]
Add tag for browser-specific support (closing #61 as duplicate)

**Comment by collinbarrett** [comment]
Some tags will be hard-coded in the dataset, some can be auto-generated.

For example, we should add a tag for "New" per #271 that can be auto-generated based on the date it was added. Closing #271 into this as a duplicate.

**Comment by DandelionSprout** [comment]
On top of the 9-ish topic tags that have been suggested above, I could very well also suggest the following ones:

`Miscellaneous/Variety` (Examples: Anti-IMDB List; Dandelion Sprout's Website Stretcher; Dandelion Sprout's Redirector List; Generic Annoying Stickybar Filter v2?; HOSTS AdBlock - Anti-Annoyance - ReStyle Annoying Pages; I Don't Care About Emojis; Mute)
`Proxy hosts` (Examples: Go Hosts; Google Hosts)
`Search results` (Examples: Dandelion Sprout's list for Chrome Personal Blocklist; Blocklist (ligyxy); LeeCh List?; AFNIL)
`For researchers` (Example: DNS-BH Bulk Registrars; most others of DNS-BH's lists)
`Cashback whitelists` (Examples: Ebates Cash Back Shopping; Shopping Whitelist BarclayCard; Norwegian Cashback Helper)

If any of the above categories are not included, they can be incorporated into `Miscellaneous/Variety` instead, as that category would be one that I'd love to see, as it'd serve as some kind of guide as to what kind of inventive things adblockers can be used for.

**Comment by collinbarrett** [comment]
added to wiki:

- [Tag](https://github.com/collinbarrett/FilterLists/wiki/Tag)
- [FilterListTag](https://github.com/collinbarrett/FilterLists/wiki/FilterListTag)

**Comment by collinbarrett** [comment]
In https://github.com/collinbarrett/FilterLists/commit/bac9f99416b4a1b426e9da53a330c9f8004bd91c , I added a proof of concept to the main grid. Search for list "NoCoin" or for tag "crypto". Hover over the tag to see the description in the html title.

It still needs line breaks for multiple tags, and dynamic colors (by tag), most notably.

If you don't see it yet, it may take at least 4 hours from when I'm writing this for the caching layers to purge.
